package jose.aos.entitis;
// Generated 27-jun-2017 12:19:59 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RegistroSec generated by hbm2java
 */
@Entity
@Table(name = "REGISTRO_SEC", schema = "HR")
public class RegistroSec implements java.io.Serializable {

	private BigDecimal idSec;

	public RegistroSec() {
	}

	public RegistroSec(BigDecimal idSec) {
		this.idSec = idSec;
	}

	@Id

	@Column(name = "ID_SEC", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdSec() {
		return this.idSec;
	}

	public void setIdSec(BigDecimal idSec) {
		this.idSec = idSec;
	}

}
