package jose.aos.entitis;
// Generated 27-jun-2017 12:19:59 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.*;

/**
 * RegistroTabla generated by hbm2java
 */
@Entity
@Table(name = "REGISTRO_TABLA", schema = "HR")
@TableGenerator(
		name="course",
		table ="ID_TABLA",
		pkColumnName = "secuence_name",
		valueColumnName = "nextval",
		allocationSize=30)

public class RegistroTabla implements java.io.Serializable {

	private BigDecimal id;

	public RegistroTabla() {
	}

	public RegistroTabla(BigDecimal id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.TABLE, generator="course")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

}
